---
- debug:
    msg: "Install dependencies"
- debug:
    msg: "Build angular application"
- name: clone repo
  git:
      repo: "{{ repo_url }}"
      dest: "{{ repo_absolute_path }}"
  when: git_directory.stat.exists == False
- name: Install service packages based on PATH/package.json
  npm:
      path: "{{ repo_absolute_path }}"
- name: Build angular
  command: "chdir={{ repo_absolute_path }} node ./node_modules/.bin/ng build --configuration=production"
