---
- debug:
    msg: "EC2 instance shall have s3 write access role"
- debug:
    msg: "aws s3 cp --recursive {{ repo_absolute_path }}/dist/ {{ cdn_bucket_uri }} --acl public-read"
# Use ansible module instead
- name: copy files to s3
  command: "aws s3 cp --recursive {{ repo_absolute_path }}/dist/ {{ cdn_bucket_uri }} --acl public-read"

