---
- set_fact: repo_url="{{repo_url}}"
- set_fact: repo_absolute_path="/srv/angular-build"
- set_fact: cdn_bucket_uri="{{cdn_bucket_uri}}"
- name: check if sources exist
  stat:
    path: "{{ repo_absolute_path }}"
  register: git_directory
- debug:
    msg: "Does git_directory exists => {{git_directory.stat.exists}}"
