---
- hosts: database
  remote_user: ubuntu
  tasks:
  - set_fact: vars_file="default"
    when: vars_file is undefined
  - name: include variables
    include_vars: vars/{{vars_file}}.yml
  - import_tasks: playbooks/parts/database/mysql-drop.yml
  - import_tasks: playbooks/parts/database/mysql-checkup.yml
