---
- hosts: lambda-server
  remote_user: ubuntu
  tasks:
    - set_fact: vars_file="default"
      when: vars_file is undefined
    - name: include variables
      include_vars: vars/{{vars_file}}.yml
    - import_tasks: playbooks/parts/spa/checks.yml
    - import_tasks: playbooks/parts/spa/angular-build.yml
    - import_tasks: playbooks/parts/spa/aws-s3-deploy.yml
