database-create:
  inputs:
    - environment
    - service-deployment
  variables:
    - key: db_hostname
      required: true
    - key: db_database
      required: true
    - key: db_username
      required: true
    - key: db_password
      required: true
database-drop:
  inputs:
    - environment
    - service-deployment
  variables:
    - key: db_hostname
      required: true
    - key: db_database
      required: true
    - key: db_username
      required: true
    - key: db_password
      required: true
computing-create:
  inputs:
    - environment
    - service-deployment
  variables:
    - key: repo_url
      required: true
    - key: repo_directory
      required: true
    - key: redis_hostname
      required: true
    - key: db_hostname
      required: true
    - key: db_database
      required: true
    - key: db_username
      required: true
    - key: db_password
      required: true
    - key: service_port
      required: true
    - key: github_client_id
      required: true
    - key: github_client_secret
      required: true
proxy-reload:
  inputs:
    - environment
spa-deploy:
  inputs:
    - environment
    - lambda-server
  variables:
    - key: cdn_path
      required: true
